# Generated by Django 5.1 on 2024-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modification',
            unique_together={('reduction_strategy', 'source', 'start_year')},
        ),
        migrations.AlterField(
            model_name='modification',
            name='calculation_year',
            field=models.PositiveSmallIntegerField(default=2024, help_text='Specific year for which this modification is calculated'),
        ),
    ]
