# Generated by Django 5.1 on 2024-08-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_modification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modification',
            options={'ordering': ['start_year', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='modification',
            unique_together={('reduction_strategy', 'source', 'start_year', 'order')},
        ),
    ]
