# Generated by Django 5.1 on 2024-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_alter_modification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='value',
            field=models.DecimalField(decimal_places=4, help_text='New value or ratio to apply', max_digits=10),
        ),
    ]
