# Generated by Django 5.1 on 2024-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_alter_modification_target_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='emission_factor',
            field=models.DecimalField(decimal_places=4, help_text='Emission factor (e.g., kg CO2e per unit)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of items (e.g., number of vehicles)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Annual usage or distance for a single unit', max_digits=10),
        ),
    ]
